name: ResGhostBlockFix
version: '1.0.2'
main: com.chiliasmstudio.ResGhostBlockFix.ResGhostBlockFix
api-version: '1.21'
folia-supported: true
dependencies:
  server:
    Residence:
      load: BEFORE
      required: true
      join-classpath: true